pub mod adapters;
pub mod cleaner;
pub mod cli;
pub mod config;
pub mod daemon;
pub mod discovery;
pub mod doctor;
pub mod exclude;
pub mod git;
pub mod install;
pub mod materializer;
pub mod migration;
pub mod observe;
pub mod purge;
pub mod reconciler;
pub mod reporting;
pub mod repos;
pub mod service;
pub mod state;
pub mod watch;

pub use config::{AppConfig, LoadedConfig};
